### PR TITLE
feat: implement failed mutations log

### PR DESCRIPTION
**Pull request by dopiera**
This PR implements the failed mutation log. Its design is documented in the `README.md` in the `faillog` package.

It uses the existing `faillog.Appender` to write data to files. Serialization is performed by dumping the mutations and their context to JSON. The part of the JSON corresponding to the mutation itself is obtained by utilizing HBase client internals, which convert the relevant `Mutation`s to protocol buffers. These protocol buffers are then translated into JSON. The translation is tricky due to protocol buffers being shaded - please refer to the class description for more details.

The `Logger` class is to be plugged into the `MirroringClient` in another PR.

---
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19)

### CODE REVIEW

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
I've left some comments, nitpicks mostly. I cannot see any prettier way of serializing the protobufs, but honsetly I'm not sure if dumping mutation contents to full json instead of base64 representation of protobuf bytes will be useful to the users. Dumping protobufs to JSON is the most complicated part of this code and I don't think that examining exact contents of mutations that have failed would be useful to anyone who just want to replay them onto the secondary database when problems are over.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-:-MkM5Mp4DqfF85U5AD_h:bs8jzrs)* status: 0 of 9 files reviewed, 10 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Appender.java, line 37 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJfsn99PnEho4qGg-N:-MkJfsn99PnEho4qGg-O:b-uuls8t) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Appender.java#L37)):*
> ```Java
>  * <p>Implementations should be thread-safe.
>  */
> public abstract class Appender implements AutoCloseable {
> ```

It looks like if it should be an interface, not a class. 
An interface is not permitted to have static methods, but I'd argue that we do not need them.

Currently `CreateDefault` is used to hide `DefaultAppender` as an implementation detail, in order to allow the users, i presume, to create loggers using `new Logger(Appender.CreateDefault(), new MySerializer())`. However I think that it won't work that way, because it would force users to pass such a `Logger` to a `Connection` somehow, what would prevent them from using `connectionFactory`. What we can do instead is to create a configuration parameter `FAILLOG_APPENDER_CLASS_IMPL` and use its value to create instances of appropriate class, by default our `DefaultAppender`, or any other user-defined class. I'd also argue that such a implementation should have a `MyAppender(Configuration configuration)` constructor that would read parameters from configuration file, because those parameters might be different for different implementations.

The same applies to `Serializer`.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Appender.java, line 49 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJgwNKEWkIM3ba_239:-MkJgwNKEWkIM3ba_23A:b-k5tbqu) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Appender.java#L49)):*
> ```Java
>    * details.
>    */
>   public static Appender CreateDefault(String pathPrefix, int maxBufferSize, boolean dropOnOverflow)
> ```

According to the style guide methods names should be written using `camelCalse`, not `CamelCase`.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Appender.java, line 63 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJk2So58vtEjzeHfGM:-MkJk2So58vtEjzeHfGN:b-pk6oxp) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Appender.java#L63)):*
> ```Java
>  * performed by a separate thread, which objects of this class create.
>  */
> class DefaultAppender extends Appender {
> ```

This class should be moved to a separate file. The style guide forbids multiple top-level classes in single file.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/JsonSerializer.java, line 67 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJcVS_-7Mu890dL3DS:-MkJcVS_-7Mu890dL3DT:b-o5nrke) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/JsonSerializer.java#L67)):*
> ```Java
>       return translated;
>     }
>     ArrayList<Descriptors.FileDescriptor> deps = new ArrayList<>();
> ```

nit: This method is currently responsible for handling cache entries and creating new `translated`. Creating new `translated` can be extracted to a separate method to make the code simpler.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/JsonSerializer.java, line 104 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkLwZUpDxQsYXYKgKZk:-MkLwZUpDxQsYXYKgKZl:b-qzcnkc) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/JsonSerializer.java#L104)):*
> ```Java
>     Descriptors.Descriptor translatedMessageDescriptor =
>         translatedFileDescriptor.findMessageTypeByName(typeName);
>     DynamicMessage translatedMessage = null;
> ```

Nit: Declaration and assignment in `try` block can be merged.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Logger.java, line 27 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJlU2p5y3gtjAl-9U9:-MkJlU2p5y3gtjAl-9UA:b-h8yl2b) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Logger.java#L27)):*
> ```Java
>  */
> public class Logger implements AutoCloseable {
>   Serializer serializer;
> ```

`private final`?
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Logger.java, line 76 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJlo951MY0lNXUI7tB:-MkJlo951MY0lNXUI7tC:bkjxtpv) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Logger.java#L76)):*
> ```Java
>    * @throws InterruptedException in case the appender thread was interrupted
>    */
>   void mutationFailed(Mutation mutation, Throwable failureCause) throws InterruptedException {
> ```

`RowMutations` won't be accepted here, is this intended and users should pass each mutation separately?
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java, line 23 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJn3_C0yA336duW1Po:-MkJn3_C0yA336duW1Pp:b-fpqve6) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java#L23)):*
> ```Java
> import java.nio.charset.StandardCharsets;
> import java.util.Date;
> import org.apache.hadoop.hbase.client.*;
> ```

The style guide forbids `*` imports.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java, line 69 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkLwwqQ4dXkh5xZKPwd:-MkLwwqQ4dXkh5xZKPwe:bsy1qz3) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java#L69)):*
> ```Java
>   @Override
>   public byte[] serialize(Mutation mutation, Throwable failureCause) {
>     ClientProtos.MutationProto.MutationType mutationType;
> ```

I think that embeding `MutationType` as a field into `OperatoinType` and moving those branches to a separate static method returning `OperationType` would increase readability.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/SerializerTest.java, line 20 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkM4E9291sQQFVpH-Bh:-MkM4E9291sQQFVpH-Bi:b-2zfsvh) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/SerializerTest.java#L20)):*
> ```Java
> import static org.hamcrest.CoreMatchers.containsString;
> import static org.hamcrest.CoreMatchers.equalTo;
> import static org.hamcrest.MatcherAssert.assertThat;
> ```

Is there any reason for using this library instead of Google Truth which supports `assertThat(x).isEqualTo(y)` constructs, which, by the way, you wanted me to use some time ago? :D

**Review by dopiera — COMMENTED** [review]
That is a good point. I think it has the benefit of being able to read the logs without a custom tool (and also be able to query the logs in e.g. kibana, so that the user can ignore the mutations they don't care about.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-:-MkbOZ6I8ri8IqL2vO-j:b-nk1lsk)* status: 0 of 11 files reviewed, 8 unresolved discussions (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Appender.java, line 37 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJfsn99PnEho4qGg-N:-MkbUSiH3Yj7HTUlrvpE:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Appender.java#L37)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

It looks like if it should be an interface, not a class. 
An interface is not permitted to have static methods, but I'd argue that we do not need them.

Currently `CreateDefault` is used to hide `DefaultAppender` as an implementation detail, in order to allow the users, i presume, to create loggers using `new Logger(Appender.CreateDefault(), new MySerializer())`. However I think that it won't work that way, because it would force users to pass such a `Logger` to a `Connection` somehow, what would prevent them from using `connectionFactory`. What we can do instead is to create a configuration parameter `FAILLOG_APPENDER_CLASS_IMPL` and use its value to create instances of appropriate class, by default our `DefaultAppender`, or any other user-defined class. I'd also argue that such a implementation should have a `MyAppender(Configuration configuration)` constructor that would read parameters from configuration file, because those parameters might be different for different implementations.

The same applies to `Serializer`.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Appender.java, line 49 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJgwNKEWkIM3ba_239:-MkbUUAJ75PDYIBI--St:ba3dfob) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Appender.java#L49)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

According to the style guide methods names should be written using `camelCalse`, not `CamelCase`.
</blockquote></details>

Removed
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Appender.java, line 63 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJk2So58vtEjzeHfGM:-MkbUVts1iegsPOMcKUg:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Appender.java#L63)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

This class should be moved to a separate file. The style guide forbids multiple top-level classes in single file.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/JsonSerializer.java, line 67 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJcVS_-7Mu890dL3DS:-MkbWQwnE3tgFfykrWxm:bb6un1j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/JsonSerializer.java#L67)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

nit: This method is currently responsible for handling cache entries and creating new `translated`. Creating new `translated` can be extracted to a separate method to make the code simpler.
</blockquote></details>

Done
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Logger.java, line 27 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJlU2p5y3gtjAl-9U9:-MkbWdoi6iPwTj1R96we:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Logger.java#L27)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

`private final`?
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Logger.java, line 76 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJlo951MY0lNXUI7tB:-MkbWegI9Ud7I7mnghsr:bwc15a5) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Logger.java#L76)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

`RowMutations` won't be accepted here, is this intended and users should pass each mutation separately?
</blockquote></details>

Yes that was the intention. If we want some additional context (e.g. index of the mutation in a batch accompanied by some opaque batch ID, we could add that later.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java, line 23 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJn3_C0yA336duW1Po:-MkbXXvM984gTd8CF3qI:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java#L23)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

The style guide forbids `*` imports.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java, line 69 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkLwwqQ4dXkh5xZKPwd:-MkbYWdt7q6qXz4qLimF:b2ns5oh) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java#L69)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I think that embeding `MutationType` as a field into `OperatoinType` and moving those branches to a separate static method returning `OperationType` would increase readability.
</blockquote></details>

OperationType is serializable. We could do this, but suddenly we'd be serializing two names of the same thing (awkward) or we'd have to make deserialization non-trivial (less readable than what we have, I think). Without this, we have the problem of returning a pair, so we'd have to have two mappings, yielding it also less readable IMO.

But maybe I'm missing some obvious solution?
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/SerializerTest.java, line 20 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkM4E9291sQQFVpH-Bh:-MkbZFdm5VG4wC1QShow:bnj3owz) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/SerializerTest.java#L20)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Is there any reason for using this library instead of Google Truth which supports `assertThat(x).isEqualTo(y)` constructs, which, by the way, you wanted me to use some time ago? :D 
</blockquote></details>

Not really :) Let me redo this.

**Review by prawilny — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 6 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19)* status: all files reviewed, 8 unresolved discussions (waiting on @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java, line 23 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJn3_C0yA336duW1Po:-MkfpOH1-bQ2ZSBzQE9j:b-k8w4ih) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java#L23)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not in all of the files

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 4 of 8 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19)* status: all files reviewed, 4 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/DefaultSerializer.java, line 60 at r3](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-Mkfs6FGEPC18UozlUox:-Mkfs6FGEPC18UozlUoy:b-6llv5f) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/4f4fe5581d23e4796c5bdfbbf8da0d62b4a497c2/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/DefaultSerializer.java#L60)):*
> ```Java
>       operationType = LogEntry.OperationType.PUT;
>     } else {
>       throw new RuntimeException("Invalid mutation type: " + mutation.getClass().toString());
> ```

nit: I think that`IllegalArgumentException` would be more specific.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/DefaultSerializer.java, line 63 at r3](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-Mkfslz_DIIXoDkPB-GH:-Mkfslz_DIIXoDkPB-GI:bu8n792) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/4f4fe5581d23e4796c5bdfbbf8da0d62b4a497c2/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/DefaultSerializer.java#L63)):*
> ```Java
>     }
>     try {
>       ClientProtos.MutationProto mutationProto =
> ```

nit: I think that this moving this to a separate `serializeMutationToProtobuf(mutationType, mutation)` would make this method more readable.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java, line 69 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkLwwqQ4dXkh5xZKPwd:-Mkflze51hW9H0ZF70c0:bebx389) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java#L69)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

OperationType is serializable. We could do this, but suddenly we'd be serializing two names of the same thing (awkward) or we'd have to make deserialization non-trivial (less readable than what we have, I think). Without this, we have the problem of returning a pair, so we'd have to have two mappings, yielding it also less readable IMO.

But maybe I'm missing some obvious solution?
</blockquote></details>

Maybe I'm wrong, but from what I have seen in your tests and somwhere in documentation, enums are serialized as enum constant name (e.g. `"PUT"`), not as their contents (`{"name": "put"}` etc.), unless explicitly annotated to be handled otherwise. Or are we talking about different serializations?
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/DefaultSerializerTest.java, line 31 at r3](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkfnvG30gkDS1mpMCpF:-MkfnvG30gkDS1mpMCpG:b-nghcg6) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/4f4fe5581d23e4796c5bdfbbf8da0d62b4a497c2/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/DefaultSerializerTest.java#L31)):*
> ```Java
> import org.apache.hadoop.hbase.Cell;
> import org.apache.hadoop.hbase.CellScanner;
> import org.apache.hadoop.hbase.client.*;
> ```

`*` import.

**Review by dopiera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java, line 23 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkJn3_C0yA336duW1Po:-MkrfxPECmsznlouTBFX:b-i5wwsb) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java#L23)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Not in all of the files
</blockquote></details>

Ooops, fixed now.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java, line 69 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkLwwqQ4dXkh5xZKPwd:-MkriPqX3emv-DZtbJVs:b-rdrdf4) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/3d55375c2f56274adfecaab338b7da4e70b6e320/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/Serializer.java#L69)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Maybe I'm wrong, but from what I have seen in your tests and somwhere in documentation, enums are serialized as enum constant name (e.g. `"PUT"`), not as their contents (`{"name": "put"}` etc.), unless explicitly annotated to be handled otherwise. Or are we talking about different serializations?
</blockquote></details>

You're right, it is smarter than I thought.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/DefaultSerializerTest.java, line 31 at r3](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19#-MkfnvG30gkDS1mpMCpF:-MkriUOfARwRYOHq6zhD:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/4f4fe5581d23e4796c5bdfbbf8da0d62b4a497c2/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/faillog/DefaultSerializerTest.java#L31)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

`*` import.
</blockquote></details>

Done.

**Review by mwalkiewicz — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dopiera)

**Pull request merged**
