### PR TITLE
refactor: split SplitBatchResponse

### PR DESCRIPTION
**Pull request by mwalkiewicz**
SplitBatchResponse was refactored into two parts: splitting into
reads/writes and failed/successful. This makes the code simpler and
easier to maintain.

---
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/40)

### CODE REVIEW

**Review by prawilny — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/40)* status: all files reviewed, 3 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java, line 198 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/40#-Mkw-XHACUPQdrb0L8CK:-Mkw-XHACUPQdrb0L8CL:b-iseexp) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/a67f521072b8f9fa47a689742e332ca3506d3907/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java#L198)):*
> ```Java
> 
>   /**
>    * Helper class facilitating analysis of {@link Table#batch(List, Object[])} results. Splits
> ```

Shouldn't the link be to MirroringTable?
Also, please add link to MirroringAsyncTable#batch.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java, line 220 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/40#-Mkw00Kd04uDhU2kRESI:-Mkw00Kd04uDhU2kRESJ:bybhp2f) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/a67f521072b8f9fa47a689742e332ca3506d3907/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java#L220)):*
> ```Java
>         } else {
>           successfulOperations.add(operation);
>           successfulResultsList.add((Result) result);
> ```

Yesterday we talked about making it possible to use this function to split results of exists(List<Get>). Isn't it possible?
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java, line 229 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/40#-Mkw0YLW04p85zCZM_92:-Mkw0YLW04p85zCZM_93:b-bbjtfk) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/a67f521072b8f9fa47a689742e332ca3506d3907/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java#L229)):*
> ```Java
> 
>   /**
>    * Helper class facilitating analysis of {@link Table#batch(List, Object[])} results. Splits
> ```

Once again I think a link to AsyncTable is sensible.

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/40)* status: all files reviewed, 3 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java, line 220 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/40#-Mkw00Kd04uDhU2kRESI:-MkwIEPp1U3u4hjL5lk8:b5k497i) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/a67f521072b8f9fa47a689742e332ca3506d3907/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java#L220)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Yesterday we talked about making it possible to use this function to split results of exists(List<Get>). Isn't it possible?
</blockquote></details>

Locally I changed the type of `successfulReads` (and some other variables) to `Object[]` and it seems to work (the tests pass). That's what I work with on generalBatch().

**Review by mwalkiewicz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/40)* status: all files reviewed, 3 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java, line 198 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/40#-Mkw-XHACUPQdrb0L8CK:-MkwSeVF126KqKZzbG-2:b-9gv6lu) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/a67f521072b8f9fa47a689742e332ca3506d3907/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java#L198)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Shouldn't the link be to MirroringTable?
Also, please add link to MirroringAsyncTable#batch.
</blockquote></details>

In fact, we use it to analyze results of `Table#batch` inside of `MirroringTable#batch`
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java, line 220 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/40#-Mkw00Kd04uDhU2kRESI:-MkwSow10aYQr5VvTIbL:b-o0c568) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/a67f521072b8f9fa47a689742e332ca3506d3907/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java#L220)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Locally I changed the type of `successfulReads` (and some other variables) to `Object[]` and it seems to work (the tests pass). That's what I work with on generalBatch(). 
</blockquote></details>

I know we did, but let's change one thing at a time. I'll leave it to you to modify types to support that case, because you have code to test in on. You can take a look at `ReadWriteSplit` on how to create an array of generic type. Maybe you will be able to use it.

**Review by dopiera — APPROVED** [review]
I think this is great!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/40#-:-Ml9ju4-4tTFwmOn5we7:bqztevm)* status: all files reviewed, 3 unresolved discussions (waiting on @mwalkiewicz and @prawilny)

**Pull request merged**
