### PR TITLE
feat: defer closing connections until async operations complete

### PR DESCRIPTION
**Pull request by prawilny**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37)

### CODE REVIEW

**Review by dopiera — CHANGES_REQUESTED** [review]
Reference counting is only an implementation detail, please adjust the commit message to reflect what you're changing and why. E.g.
> feat: defer closing connections until async operations complete
>
> Mirroring client schedules asynchronous operations - to mirror the mutations and to verify reads. Before this PR, closing the `MirroringClient` would result in closing the underlying clients immediately. This made the pending asynchronous operations fail. This PR defers closing the underlying clients until all pending operations complete. It is achieved by reference counting the operations.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-:-Mkm90-8DWj1VLhI5dVg:b1jnfvc)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 119 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MkmAnqp-y2z4xiMox9e:-MkmAnqp-y2z4xiMox9f:b-cgwvbc) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/39cec5c0bafdda31ef4bbe251c66c70447e30a79/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L119)):*
> ```Java
> 
>   @Override
>   public boolean isClosed() {
> ```

I think hbase connections should be thread safe. This is not.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 88 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MkmDjr37sYmKJF93Hx4:-MkmDjr37sYmKJF93Hx5:brhs2e8) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/39cec5c0bafdda31ef4bbe251c66c70447e30a79/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L88)):*
> ```Java
>   }
> 
>   private CompletableFuture<Void> createReferenceHoldingFuture() {
> ```

I don't understand why it needs to be a future. We are using it as if it was a simple callback.

I thought the idea to use the future was to simply add one continuation to all verifications and be done with it. Correct me if I'm wrong, but the way it's written we may just as well call `referenceCounter.incrementReferenceCount()`everywhere, where you call `createReferenceHoldingFuture` and call `referenceCounter.decrementReferenceCount()` everywhere, where you call `complete(null)`. If that's the case, it would be much simpler, no?

**Review by prawilny — COMMENTED** [review]
Will use the provided title and message.
Applied the suggestions.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-:-MkqQQOY3No0RHoaLVcA:b-6sae4p)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 119 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MkmAnqp-y2z4xiMox9e:-MkqRaWZ9UWBGXG4mJqn:b-9662u6) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/39cec5c0bafdda31ef4bbe251c66c70447e30a79/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L119)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think hbase connections should be thread safe. This is not.
</blockquote></details>

Used `synchronized` in close() signature.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 88 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MkmDjr37sYmKJF93Hx4:-MkqQYJxEX0zK0FxilVB:badoecl) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/39cec5c0bafdda31ef4bbe251c66c70447e30a79/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L88)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I don't understand why it needs to be a future. We are using it as if it was a simple callback.

I thought the idea to use the future was to simply add one continuation to all verifications and be done with it. Correct me if I'm wrong, but the way it's written we may just as well call `referenceCounter.incrementReferenceCount()`everywhere, where you call `createReferenceHoldingFuture` and call `referenceCounter.decrementReferenceCount()` everywhere, where you call `complete(null)`. If that's the case, it would be much simpler, no?
</blockquote></details>

Changed to ReferenceCounter

**Review by dopiera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 119 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MkmAnqp-y2z4xiMox9e:-Mkr-VLM5albmGCLdQKR:b-5ya020) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/39cec5c0bafdda31ef4bbe251c66c70447e30a79/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L119)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Used `synchronized` in close() signature.
</blockquote></details>

That, unfortunately is not enough. `isClosed()` may return stale data.

**Review by mwalkiewicz — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 88 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MkmDjr37sYmKJF93Hx4:-Mkv8Ga17Ec6wyLp7Qs9:byg48n4) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/39cec5c0bafdda31ef4bbe251c66c70447e30a79/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L88)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Changed to ReferenceCounter
</blockquote></details>

I think that the code now is more complicated, because reference counting logic leaks into handling operations and it is easy now to accidentally skip one increase/decrease.

If we placed reference counting logic into a callback with a pleasant name (`pleaseCallMeWhenAllOperationsAreDone` :) ) wouldn't have to worry about "reference counting", but only about "calling operation done callback", which is explicit, simple and it is obvious when to call it. This will make the code easier to maintain IMO.

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 88 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MkmDjr37sYmKJF93Hx4:-Ml9ncWm7zjLVL93jq-E:b-t1j8yg) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/39cec5c0bafdda31ef4bbe251c66c70447e30a79/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L88)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I think that the code now is more complicated, because reference counting logic leaks into handling operations and it is easy now to accidentally skip one increase/decrease.

If we placed reference counting logic into a callback with a pleasant name (`pleaseCallMeWhenAllOperationsAreDone` :) ) wouldn't have to worry about "reference counting", but only about "calling operation done callback", which is explicit, simple and it is obvious when to call it. This will make the code easier to maintain IMO.
</blockquote></details>

I'd argue if it would be more readable. IMO, initially, that looks great, but after a while, you forget what an "operation" is (think batch) and what "done" is (successful, failed, or maybe reported to the user), so you need to see what it does anyway, which means more things to comprehend rather than fewer. Perhaps it's just a taste thing, though.

Either way, I think we can at least make it a method rather a callback/future passed around, which I'd strongly argue is more readable (smaller method signatures and most importantly no IoC; when you have IoC you need to know all the callers to reason about what is going on there).

I don't have a strong preference for a method or the decrement directly, but I think this isn't a case for IoC.

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java, line 119 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MkmAnqp-y2z4xiMox9e:-MlFOJlkDIslEtiZSIAr:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/39cec5c0bafdda31ef4bbe251c66c70447e30a79/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncConnection.java#L119)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

That, unfortunately is not enough. `isClosed()` may return stale data.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 88 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MkmDjr37sYmKJF93Hx4:-MlFQs3_3NRzOU0Ngv9j:b6cs48m) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/39cec5c0bafdda31ef4bbe251c66c70447e30a79/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L88)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I'd argue if it would be more readable. IMO, initially, that looks great, but after a while, you forget what an "operation" is (think batch) and what "done" is (successful, failed, or maybe reported to the user), so you need to see what it does anyway, which means more things to comprehend rather than fewer. Perhaps it's just a taste thing, though.

Either way, I think we can at least make it a method rather a callback/future passed around, which I'd strongly argue is more readable (smaller method signatures and most importantly no IoC; when you have IoC you need to know all the callers to reason about what is going on there).

I don't have a strong preference for a method or the decrement directly, but I think this isn't a case for IoC.
</blockquote></details>

I rewrote it a bit: there's a method that calls the reference counter and `AsyncRequestScheduling`accepts a `Runnable` argument instead of `ListenableReferenceCounter`.

**Review by prawilny — COMMENTED** [review]
The non-test code has been nearly completely rewritten.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-:-MlGFuwL8ixVh7BTdGcE:b-chxydu)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 88 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MkmDjr37sYmKJF93Hx4:-MlGGFUj-0eDL_3FORke:be3i1qe) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/39cec5c0bafdda31ef4bbe251c66c70447e30a79/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L88)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

I rewrote it a bit: there's a method that calls the reference counter and `AsyncRequestScheduling`accepts a `Runnable` argument instead of `ListenableReferenceCounter`.
</blockquote></details>

Rewrote it as written above.

**Review by prawilny — COMMENTED** [review]
I'd advise looking at full diff - it's way cleaner.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-:-MlKDzjz-RIB-hFS_x7m:b-ixuppe)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dopiera and @mwalkiewicz)

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 197 at r10](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MlRxhwFE9svJbIVzMeb:-MlRxhwFE9svJbIVzMec:b-3yuhw7) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/1def25ca21e408eb6297f0164e35ed3d3ce59d6c/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L197)):*
> ```Java
>   }
> 
>   private <T> T extractResultAndHoldReference(FutureUtils.Pair<T> pair) {
> ```

I think the change looks very good, however, I don't like this function - it seems to glue to together two completely unrelated things.

How about a different one:
```
void keepReferenceUntilOperationCompletes(CompletableFuture<Void> future) {
  referenceCounter.increment();
  fut.thenApply(() -> referenceCounter.decrement());
}
```

So that the code would look like this:
```
... primaryFuture = ...;
CompletableFuture<...> completionStages = writeWithFlowControl(...);
keepReferenceUntilOperationCompletes(stages.verificationFuture);
return completionStages.primaryFuture;
```

WDYT?
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/futures/FutureUtils.java, line 51 at r10](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MlRwwceDKFjAnfJ1TZi:-MlRwwceDKFjAnfJ1TZj:bm2242s) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/1def25ca21e408eb6297f0164e35ed3d3ce59d6c/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/futures/FutureUtils.java#L51)):*
> ```Java
>   }
> 
>   public static <T> FutureUtils.Pair<List<CompletableFuture<T>>> assignListPair(
> ```

This method is unused.

**Review by prawilny — COMMENTED** [review]
Note that I'm simultaneously fixing both PRs: this and FutureUtils one. So some changes may be fixed in the other PR. 

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-:-MlTyv3X3w9ltqp6d-ys:bop49as)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 197 at r10](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MlRxhwFE9svJbIVzMeb:-MlTqqsXAJxC_cunIL1o:bxqsnor) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/1def25ca21e408eb6297f0164e35ed3d3ce59d6c/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L197)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think the change looks very good, however, I don't like this function - it seems to glue to together two completely unrelated things.

How about a different one:
```
void keepReferenceUntilOperationCompletes(CompletableFuture<Void> future) {
  referenceCounter.increment();
  fut.thenApply(() -> referenceCounter.decrement());
}
```

So that the code would look like this:
```
... primaryFuture = ...;
CompletableFuture<...> completionStages = writeWithFlowControl(...);
keepReferenceUntilOperationCompletes(stages.verificationFuture);
return completionStages.primaryFuture;
```

WDYT?
</blockquote></details>

I feel like not incrementing the reference counter before doing all the work may possibly introduce a race condition.

Refactored the code as suggested but with the incrementation of the reference counter out of the function. 
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/futures/FutureUtils.java, line 51 at r10](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37#-MlRwwceDKFjAnfJ1TZi:-MlTqmBD8bM5oxnPeRcT:b-1xilvs) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/1def25ca21e408eb6297f0164e35ed3d3ce59d6c/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/utils/futures/FutureUtils.java#L51)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

This method is unused.
</blockquote></details>

And it never will be. Removed

**Review by dopiera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/37)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dopiera and @mwalkiewicz)

**Pull request merged**
