### PR TITLE
fix: Implement single Append and Increment as Put

### PR DESCRIPTION
**Pull request by prawilny**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)

### CODE REVIEW

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java, line 134 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkqTcak0W3_Dmb9BHm-:-MkqTcak0W3_Dmb9BHm0:b-qlg82q) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/4bd53bcba12016e41f4c2d63727f30f30ce993bc/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java#L134)):*
> ```Java
>   }
> 
>   public static Put makePutFromResult(Result result) {
> ```

If you want to reuse this method move it to a separate package/class and use it in both places. Helper method do not belong to a public API of a class, unless it is a class with helpers.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 115 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkqURPfErbimdhtXTz2:-MkqURPfErbimdhtXTz3:b-nekv9j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/4bd53bcba12016e41f4c2d63727f30f30ce993bc/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L115)):*
> ```Java
> 
>     CompletableFuture<Result> primaryFuture = this.primaryTable.append(append);
>     primaryFuture.whenComplete(
> ```

Instead of copying the logic twice extract it to a separate method. Maybe you can integrate it somehow with 
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 128 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkqUvw26wEAjuXGgVbn:-MkqUvw26wEAjuXGgVbo:b-e1eqmo) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/4bd53bcba12016e41f4c2d63727f30f30ce993bc/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L128)):*
> ```Java
>               .whenComplete(
>                   (ignoredResult, ignoredError) -> {
>                     resultFuture.complete(primaryResult);
> ```

The resultFuture is completed after both operation are completed, not after reservation is taken. Please do not reinvent logic that is already implemented, try to make it generic and reuse it.

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 115 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkqURPfErbimdhtXTz2:-MkqYoua5ZrauW21nUyw:b-ci5v70) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/4bd53bcba12016e41f4c2d63727f30f30ce993bc/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L115)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Instead of copying the logic twice extract it to a separate method. Maybe you can integrate it somehow with 
</blockquote></details>

... with writeWithFlowControl, e.g. by using just a little more generics.

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dopiera, @mwalkiewicz, and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 115 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkqURPfErbimdhtXTz2:-Mkr6J7G99d9cuqIS6rJ:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/4bd53bcba12016e41f4c2d63727f30f30ce993bc/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L115)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

... with writeWithFlowControl, e.g. by using just a little more generics.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 128 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkqUvw26wEAjuXGgVbn:-Mkr6Ida-_dORvlJ6cEd:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/4bd53bcba12016e41f4c2d63727f30f30ce993bc/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L128)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

The resultFuture is completed after both operation are completed, not after reservation is taken. Please do not reinvent logic that is already implemented, try to make it generic and reuse it.
</blockquote></details>

Done.

**Review by dopiera — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java, line 134 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkqTcak0W3_Dmb9BHm-:-MkrBdzs1Cs2E_KWwTIM:b32v57) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/4bd53bcba12016e41f4c2d63727f30f30ce993bc/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java#L134)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

If you want to reuse this method move it to a separate package/class and use it in both places. Helper method do not belong to a public API of a class, unless it is a class with helpers.
</blockquote></details>

+1

**Review by prawilny — COMMENTED** [review]
> Dismissed @mwalkiewicz from a discussion.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java, line 134 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkqTcak0W3_Dmb9BHm-:-MkrIIfT8gzx8tJlBjQx:b-cf3fg4) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/4bd53bcba12016e41f4c2d63727f30f30ce993bc/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java#L134)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done. I forgot about it last time.

**Review by dopiera — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: all files reviewed, 2 unresolved discussions (waiting on @mwalkiewicz)

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: all files reviewed, 1 unresolved discussion (waiting on @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 135 at r3](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkvU4jD0toY9AmiQxup:-MkvU4jEC92s5U_twpIw:b-vb6rr) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/f49f4708c9edb732289f16d08d9b1ebe46dbb9fb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L135)):*
> ```Java
>         HBaseOperation.INCREMENT,
>         primaryTable.increment(increment),
>         () -> this.secondaryWriteErrorConsumer.consume(HBaseOperation.INCREMENT, increment));
> ```

We should use converted `Put` here. It'd be the best to move this handler to `mutationViaPut`.

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 135 at r3](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkvU4jD0toY9AmiQxup:-MkwCPeS6S1kvX4yFteO:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/f49f4708c9edb732289f16d08d9b1ebe46dbb9fb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L135)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

We should use converted `Put` here. It'd be the best to move this handler to `mutationViaPut`.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 287 at r4](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkwCSDu7F2w9baETjZo:-MkwCSDvCa3zAw3kK1HG:b1dutbr) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/307d972504b6629fc644bf33c4d474abc01c49a9/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L287)):*
> ```Java
>                   () -> this.secondaryTable.put(put),
>                   () -> secondaryPutWriteErrorHandler.accept(put))
>               .whenComplete(
> ```

Fixed a bug with too early completion of the result future. As I wrote somewhere else, I hope at some point I'll find time to create some shared functions to reduce such boilerplate.

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: all files reviewed, 5 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 135 at r3](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkvU4jD0toY9AmiQxup:-Ml08Ac83wFma3y56Yj8:b9oxukd) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/f49f4708c9edb732289f16d08d9b1ebe46dbb9fb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L135)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You should pass HBaseOperation.PUT here and in append. Then you can move creating this handler mutationAsPut.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 287 at r4](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkwCSDu7F2w9baETjZo:-Ml08X1bEM3Cgmd_kMA7:b-349b44) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/307d972504b6629fc644bf33c4d474abc01c49a9/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L287)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Fixed a bug with too early completion of the result future. As I wrote somewhere else, I hope at some point I'll find time to create some shared functions to reduce such boilerplate.
</blockquote></details>

You can surely do this when you finish currently opened tasks. I do not think that we are in a rush.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 591 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-Ml09-scAQ2mP3P35Zm2:-Ml09-scAQ2mP3P35Zm3:blsgfyy) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8a66cfb583337496f393f2ceea6da0f807e37738/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L591)):*
> ```Java
>   }
> 
>   private void assertPutsAreEqual(Put expectedPut, Put value) {
> ```

Can we add a dependency to 1.x tests and use method defined there? I think it is enough of temporary copy-pastes and it's time to invent some sane solution to this problem.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 635 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-Ml09s2a6PpttZJsSsUE:-Ml09s2a6PpttZJsSsUF:b-i7b85t) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8a66cfb583337496f393f2ceea6da0f807e37738/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L635)):*
> ```Java
>     ArgumentCaptor<Put> argument = ArgumentCaptor.forClass(Put.class);
>     verify(secondaryTable, never()).increment(any(Increment.class));
>     verify(secondaryTable, times(3)).put(argument.capture());
> ```

You can just use `.put(expectedPut)` and `times(3)` will handle checking if it was called 3 times, no need to use argument captor. If you want to be sure that is was not called with any other argument, you can add a check `verify(..., times(3)).put(any())`.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 667 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-Ml0ALxe0zmHGLZPSQr4:-Ml0ALxe0zmHGLZPSQr5:b-bzyktu) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8a66cfb583337496f393f2ceea6da0f807e37738/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L667)):*
> ```Java
> 
>     ArgumentCaptor<Put> argument = ArgumentCaptor.forClass(Put.class);
>     verify(secondaryTable, times(1)).put(argument.capture());
> ```

There's no need to use ArgumentCaptor.

**Review by dopiera — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: all files reviewed, 5 unresolved discussions (waiting on @prawilny)

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: all files reviewed, 4 unresolved discussions (waiting on @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 135 at r3](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkvU4jD0toY9AmiQxup:-MlGLoka6ykgErPBUW4x:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/f49f4708c9edb732289f16d08d9b1ebe46dbb9fb/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L135)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

You should pass HBaseOperation.PUT here and in append. Then you can move creating this handler mutationAsPut.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 287 at r4](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MkwCSDu7F2w9baETjZo:-MlGLqNyA9kYo7nks22u:br90zsf) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/307d972504b6629fc644bf33c4d474abc01c49a9/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L287)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

You can surely do this when you finish currently opened tasks. I do not think that we are in a rush.
</blockquote></details>

Opened the pull request with FutureUtils.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 591 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-Ml09-scAQ2mP3P35Zm2:-MlGM2AL8V8kX-cSQmyG:b-gl909a) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8a66cfb583337496f393f2ceea6da0f807e37738/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L591)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Can we add a dependency to 1.x tests and use method defined there? I think it is enough of temporary copy-pastes and it's time to invent some sane solution to this problem.
</blockquote></details>

No, there's a problem: CellComparator in HBase1 is a class and in HBase2 - an interface, so even brutally casting it doesn't work.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 635 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-Ml09s2a6PpttZJsSsUE:-MlGOpek1Gwn96t0t9qF:bx0caj7) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8a66cfb583337496f393f2ceea6da0f807e37738/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L635)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

You can just use `.put(expectedPut)` and `times(3)` will handle checking if it was called 3 times, no need to use argument captor. If you want to be sure that is was not called with any other argument, you can add a check `verify(..., times(3)).put(any())`.
</blockquote></details>

Unfortunately, there comes up a problem I couldn't google:

How should I deal with it properly?
I feel that lowering the tests' strictness (`any()`) isn't the solution.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 667 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-Ml0ALxe0zmHGLZPSQr4:-MlGMRvI5KICvYr7xX_2:b6m15ax) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8a66cfb583337496f393f2ceea6da0f807e37738/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L667)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

There's no need to use ArgumentCaptor.
</blockquote></details>

Unfortunately, there is (sameish as above)

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 591 at r5](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-Ml09-scAQ2mP3P35Zm2:-MlK_EI_2d2L4H81NooB:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/8a66cfb583337496f393f2ceea6da0f807e37738/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L591)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

OK, noted. But you can create a shared `assertPutsAreEqual(Put, Put, CellComparator)` in common package and then use it here and in 1.x tests.
</blockquote></details>

Done.

**Review by mwalkiewicz — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @prawilny)

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: all files reviewed, 1 unresolved discussion (waiting on @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 131 at r7](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38#-MleahTsDtj2jL1yXqrn:-MleahTsDtj2jL1yXqro:b-3vdz8j) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/5ec6637d9648a2cc6c694ba639f4b3d1a58c03e7/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L131)):*
> ```Java
>   public CompletableFuture<Result> append(Append append) {
>     return mutationAsPut(
>         new MirroringTable.WriteOperationInfo(append), this.primaryTable.append(append));
> ```

Bug I've just noticed in my own code, and that also applies here:
the WriteOperationInfo should be created with `Put` that will be sent to the secondary database, not with Append sent to the primary.

**Review by dopiera — APPROVED** [review]
> Reviewed 1 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: all files reviewed, 1 unresolved discussion (waiting on @prawilny)

**Review by dopiera — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @dopiera, @mwalkiewicz, and @prawilny)

**Review by mwalkiewicz — APPROVED** [review]
> Reviewed 2 of 5 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/38)* status: all files reviewed, 1 unresolved discussion (waiting on @prawilny)

**Pull request merged**
