### PR TITLE
fix: BufferedMutator close() waits for all secondary flushes to finish

### PR DESCRIPTION
**Pull request by mwalkiewicz**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/110)

### CODE REVIEW

**Review by prawilny — DISMISSED** [review]
Looks good.

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/110#-:-Mn0sgINEoQNDPymIASH:b-vs1pr4)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringBufferedMutator.java, line 455 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/110#-Mn0roaO1S8pRkMSH6oz:-Mn0roaO1S8pRkMSH6p-:b-dao7og) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c876cf18b0e8ad51e3173f4d750b7c2d740c44d6/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringBufferedMutator.java#L455)):*
> ```Java
>     for (int i = 0; i < numRunningFlushes; i++) {
>       bm.mutate(mutations);
>       // Primary flush completes immediately, secondary is blocked but releases one permit on the
> ```

Is this comment precise? Don't we set 4 * size(operation) as threshold for automatic flush (it's a conjecture) so that it isn't flushed immediately?

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/110)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringBufferedMutator.java, line 455 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/110#-Mn0roaO1S8pRkMSH6oz:-MnQrVil975Q3MfijpOw:b42z0h1) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c876cf18b0e8ad51e3173f4d750b7c2d740c44d6/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringBufferedMutator.java#L455)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I did set it to 4*size to prevent automatic flush, I want to perform it manually, which happens in the next line.
</blockquote></details>

I don't remember what happens in the code but isn't what you wrote also what I wrote?
I feel like you just contradicted the comment - it states that "Primary flush completes immediately" whereas you just said that the argument to getBufferedMutator "prevent[s] automatic flush".

**Review by mwalkiewicz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/110)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringBufferedMutator.java, line 455 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/110#-Mn0roaO1S8pRkMSH6oz:-MnklAIw1ZP9f82waM-O:b-fh0hcu) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c876cf18b0e8ad51e3173f4d750b7c2d740c44d6/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringBufferedMutator.java#L455)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

I don't remember what happens in the code but isn't what you wrote also what I wrote?
I feel like you just contradicted the comment - it states that "Primary flush completes immediately" whereas you just said that the argument to getBufferedMutator "prevent[s] automatic flush".
</blockquote></details>

What I meant by "automatic" is "periodic", but manually calling `flush()` will perform the flush. I've added a comment explaining what is going on.

**Review by prawilny — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/110)* status: all files reviewed, 1 unresolved discussion (waiting on @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringBufferedMutator.java, line 455 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/110#-Mn0roaO1S8pRkMSH6oz:-Mo3lgPS8S-WoM1pOQSg:bc3mgau) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c876cf18b0e8ad51e3173f4d750b7c2d740c44d6/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringBufferedMutator.java#L455)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

What I meant by "automatic" is "periodic", but manually calling `flush()` will perform the flush. I've added a comment explaining what is going on.
</blockquote></details>

Reviewable claims (about TestMirroringBufferedMutator.java) that `File not in pull request at selected revision.`

**Review by mwalkiewicz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/110)* status: all files reviewed, 1 unresolved discussion (waiting on @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringBufferedMutator.java, line 455 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/110#-Mn0roaO1S8pRkMSH6oz:-Mo3p8-y4MrYeCbDHHAF:bw2t9v) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c876cf18b0e8ad51e3173f4d750b7c2d740c44d6/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestMirroringBufferedMutator.java#L455)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Reviewable claims (about TestMirroringBufferedMutator.java) that `File not in pull request at selected revision.`
</blockquote></details>

Yes, in the meanwhile this file was renamed to TestSequential...

**Pull request merged**
