### PR TITLE
refactor: extract helper methods in tests

### PR DESCRIPTION
**Pull request by mwalkiewicz**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/48)

### CODE REVIEW

**Review by prawilny — APPROVED** [review]
Looks good. I'll create an issue for myself for the same thing in 2.x tests.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/48#-:-MlFGxyD7rBbLLGdcah5:b-w7b0dd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mwalkiewicz)

**Review by mwalkiewicz — COMMENTED** [review]
I've already done it, I accidentally did not commit those changes.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/48#-:-MlFa4Su5Ab6M494xmih:b-et2e0y)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @prawilny)

**Review by prawilny — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/48#-:-MlFggTk3z0NFqRE0o4s:bnfp4nl)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/pom.xml, line 97 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/48#-MlFgu0h5A2PtgSeomKO:-MlFgu0h5A2PtgSeomKP:bbuhnk2) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/541268331ea933706a134df3ff7f56c20ccc66ab/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/pom.xml#L97)):*
> ```XML
>     <dependency>
>       <groupId>com.google.cloud.bigtable</groupId>
>       <artifactId>bigtable-hbase-mirroring-client-1.x</artifactId>
> ```

(I don't know much about maven)
Don't we need some information about the new dependancy in the 2.x's pom.xml?




manual edit: retracting the comment seems not to mark it as retracted on GitHub - I checked and it runs on my machine, so I think it works okay.

**Review by prawilny — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/48)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @prawilny)

**Review by prawilny — APPROVED** [review]

**Pull request merged**
