### PR TITLE
feat: 2.x - rewrite Increment and Append as Put in batch

### PR DESCRIPTION
**Pull request by mwalkiewicz**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/116)

### CODE REVIEW

**Review by mwalkiewicz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/116)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java, line 293 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/116#-MmxA-2N0RBcGQkaF08T:-MnkumjCDIVzGATPNbMy:b-l2tt7p) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/756bcfb1faeb541f1369a38fc2288656bd64cd37/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/BatchHelpers.java#L293)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

it's already extracted into `OperationUtils` on master (unless it's been moved elsewhere)
</blockquote></details>

Done, good catch.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 779 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/116#-MmxAKyf90sCtJbTHj0h:-MnkvY5nBlkkmudXcNeo:bnkc7hs) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/756bcfb1faeb541f1369a38fc2288656bd64cd37/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L779)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

It's already extracted in `TestHelpers.java`
</blockquote></details>

Do you remember what did you refer to in this comment?

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/116)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 779 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/116#-MmxAKyf90sCtJbTHj0h:-Mo3fNnw1qu1hisce4e3:b-azeva) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/756bcfb1faeb541f1369a38fc2288656bd64cd37/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L779)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Do you remember what did you refer to in this comment?
</blockquote></details>

`TestHelpers.assertPutsAreEqual`, I think. 
Link to current master:
https://github.com/Unoperate/java-bigtable-hbase-1/blob/ac5c153624cabbcea0dcd6fb38203f2eaa8ecdbd/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestHelpers.java#L171

**Review by mwalkiewicz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/116)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @prawilny)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java, line 779 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/116#-MmxAKyf90sCtJbTHj0h:-Mo3jOCU78ZwuA73tu4P:bimhbv1) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/756bcfb1faeb541f1369a38fc2288656bd64cd37/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTable.java#L779)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

`TestHelpers.assertPutsAreEqual`, I think. 
Link to current master:
https://github.com/Unoperate/java-bigtable-hbase-1/blob/ac5c153624cabbcea0dcd6fb38203f2eaa8ecdbd/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase1_x/TestHelpers.java#L171
</blockquote></details>

OK, it was already removed.

**Review by prawilny — DISMISSED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mwalkiewicz)

**Review by prawilny — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mwalkiewicz)

**Pull request merged**
