### PR TITLE
fix: fix BufferedMutator ITs

### PR DESCRIPTION
**Pull request by mwalkiewicz**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/140)

### CODE REVIEW

**Review by prawilny — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/140)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/mirroring/TestBufferedMutator.java, line 96 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/140#-Mo4zb-K0wHIN84INtxT:-Mo4zb-K0wHIN84INtxU:bs4vzt8) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c8f0f599b6495f7fdee7fab256da11d8cccde9db/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/mirroring/TestBufferedMutator.java#L96)):*
> ```Java
>   private Configuration createConfiguration() {
>     Configuration configuration = ConfigurationHelper.newConfiguration();
>     // MirroringOptions constructor verifies that MIRRORING_SYNCHRONOUS_WRITES is true when
> ```

Tutaj lub niżej: SYNCHRONOUS => CONCURRENT/

**Review by prawilny — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/140)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/mirroring/TestBufferedMutator.java, line 96 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/140#-Mo8NC-jCJteLbjy25Mx:-Mo8NC-kDWGVmixzh2FN:b-ygjkgx) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c8f0f599b6495f7fdee7fab256da11d8cccde9db/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/mirroring/TestBufferedMutator.java#L96)):*
> ```Java
>   private Configuration createConfiguration() {
>     Configuration configuration = ConfigurationHelper.newConfiguration();
>     // MirroringOptions constructor verifies that MIRRORING_SYNCHRONOUS_WRITES is true when
> ```

Here or one line lower: SYNCHRONOUS => CONCURRENT, I think.

**Review by mwalkiewicz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/140)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/mirroring/TestBufferedMutator.java, line 96 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/140#-Mo8NC-jCJteLbjy25Mx:-Mo8QB0G1f-5JhdtuOjR:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c8f0f599b6495f7fdee7fab256da11d8cccde9db/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/mirroring/TestBufferedMutator.java#L96)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Here or one line lower: SYNCHRONOUS => CONCURRENT, I think.
</blockquote></details>

Done.

**Review by prawilny — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/140)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @mwalkiewicz)

**Pull request merged**
