### PR TITLE
refactor: implement multiple argument operations on MirroringAsyncTable with specific operations rather than batch()

### PR DESCRIPTION
**Pull request by prawilny**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/75)

### CODE REVIEW

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/75)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java, line 506 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/75#-MluMc7z9dpOf99iSFrI:-MluMc7z9dpOf99iSFrJ:b-103c9g) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/2954e53e2521c7fe818fc506dd67ec23eea2dfc9/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringAsyncTable.java#L506)):*
> ```Java
>   }
> 
>   private interface GeneralBatchBuilder {
> ```

It's a bit of a work in progress - I am yet to implement `GeneralBatchBuilder`s for Get and Mutation.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTableInputModification.java, line 121 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/75#-MluME1P22GJJbrB9LW-:-MluME1QCSM9pn4A9Edm:b7a4gar) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/2954e53e2521c7fe818fc506dd67ec23eea2dfc9/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/test/java/com/google/cloud/bigtable/mirroring/hbase2_x/TestMirroringAsyncTableInputModification.java#L121)):*
> ```Java
> 
>   @Test
>   public void testExists() throws InterruptedException, ExecutionException, TimeoutException {
> ```

It's a bit different than the rest of the tests as ExistsBuilder (implementing GeneralBatchBuilder) casts FailedSuccessfulSplit's results to boolean rather than some object type so it throws an exception if given null.

**Review by mwalkiewicz — DISMISSED** [review]
> Reviewed 1 of 5 files at r1, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/75)* status: all files reviewed, 2 unresolved discussions (waiting on @dopiera and @prawilny)

**Comment by prawilny** [comment]
Squashed the fix (of accidental raw type use) commit and rebased onto current master.

**Review by mwalkiewicz — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/75)* status: all files reviewed, 2 unresolved discussions (waiting on @dopiera and @prawilny)

**Pull request merged**
