### PR TITLE
feat: log rows and values in DefaultMismatchDetector

### PR DESCRIPTION
**Pull request by prawilny**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129)

### CODE REVIEW

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129)* status: all files reviewed, 7 unresolved discussions (waiting on @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringMetricsRecorder.java, line 83 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-MnewOO61v8sjy3acUvO:-MnewOO7Cvr8s1eb_Q8f:brtwti6) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringMetricsRecorder.java#L83)):*
> ```Java
>   }
> 
>   public void recordMatchingReads(HBaseOperation operation, int numberOfMatchingReads) {
> ```

I'd unify the name with other record* methods in this file, e.g. `recordReadMatches`.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java, line 65 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-Mnf-Jdq8YfyXEFGDKpr:-Mnf-Jdq8YfyXEFGDKps:bra3wab) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java#L65)):*
> ```Java
>           "com/google/cloud/bigtable/mirroring/mismatch/write", "Count of write mismatches.", "1");
> 
>   public static final MeasureLong MATCHING_READS =
> ```

Don't you need to define a View with this Measure? Take a look at usages of other Measures, you'll see that they are used in ...MetricViews.java file.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java, line 67 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-MneyiSD6lOznIgd2J9x:-MneyiSD6lOznIgd2J9y:b8y55zz) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java#L67)):*
> ```Java
>   public static final MeasureLong MATCHING_READS =
>       MeasureLong.create(
>           "com/google/cloud/bigtable/mirroring/matching_reads",
> ```

I'd change the naming a bit. In fact, `write mismatch` is not the best name I could have invented, it reports secondary write errors, not any mismatches :/

WDYT about changing `com/google/cloud/bigtable/mirroring/mismatch/read` into `com/google/cloud/bigtable/mirroring/read_verification/mismatches`, making this one `.../read_verification/matches`, and creating a PR for renaming `WRITE_MISMATCHES` into `SECONDARY_WRITE_ERROR`?
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java, line 63 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-MnewfXcBfFMU_b--Ota:-MnewfXcBfFMU_b--Otb:b-bw8rrr) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java#L63)):*
> ```Java
>               "existsAll(row=%s) mismatch: (%b, %b)",
>               hex(request.get(i).getRow()), primary[i], secondary[i]);
>           ++mismatches;
> ```

Why are you using pre-incrementation?
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java, line 168 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-Mnf0Skv7zox0reI9q0C:-Mnf0Skv7zox0reI9q0D:bayglpd) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java#L168)):*
> ```Java
>       }
>     }
>     if (errors != maxLength) {
> ```

Took me a while to be sure what is going on here, can we just make a separate variable `correctReads`, increment it explicitly and report it if it is `> 0`?
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java, line 177 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-Mnf2InJCkgiH5Zxes3h:-Mnf2InJCkgiH5Zxes3i:b90bz3l) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java#L177)):*
> ```Java
> 
>   private List<String> listOfHexRows(List<Get> gets) {
>     List<String> out = new ArrayList<>(gets.size());
> ```

We can make this computation lazy in the same way as `hex()`.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java, line 189 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-Mnf1bCi3fLqpuQhR54C:-Mnf1bCi3fLqpuQhR54D:b-r6ukkv) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java#L189)):*
> ```Java
>   };
> 
>   private static String hex(final byte[] bytes) {
> ```

We can easily make this computation lazy making this method return an object, that will perform the hexlification when `toString()` is called on it.

```
return new Object() {
  @Override public String toString() {
    /* body of this hex method */
  }
}
```

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringMetricsRecorder.java, line 83 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-MnewOO61v8sjy3acUvO:-MnjNjcUDtMRC63x6dsm:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringMetricsRecorder.java#L83)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I'd unify the name with other record* methods in this file, e.g. `recordReadMatches`.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java, line 65 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-Mnf-Jdq8YfyXEFGDKpr:-MnjOTdNDULxtSXlH-mH:b-yjlxlz) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java#L65)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Don't you need to define a View with this Measure? Take a look at usages of other Measures, you'll see that they are used in ...MetricViews.java file.
</blockquote></details>

I do. Didn't notice it earlier, though.
Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java, line 67 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-MneyiSD6lOznIgd2J9x:-MnjQphA-xOMW5d5-VKX:bnyq5fw) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java#L67)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I'd change the naming a bit. In fact, `write mismatch` is not the best name I could have invented, it reports secondary write errors, not any mismatches :/

WDYT about changing `com/google/cloud/bigtable/mirroring/mismatch/read` into `com/google/cloud/bigtable/mirroring/read_verification/mismatches`, making this one `.../read_verification/matches`, and creating a PR for renaming `WRITE_MISMATCHES` into `SECONDARY_WRITE_ERROR`?
</blockquote></details>

Name change of read metrics done.
Also created a PR for WRITE_MISMATCHES -> SECONDARY_WRITE_ERRORS.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java, line 63 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-MnewfXcBfFMU_b--Ota:-MnjR8hEDLhpIRzKf3cK:b-z607ml) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java#L63)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Why are you using pre-incrementation?
</blockquote></details>

I must've felt like microoptimizing (stupid, I know).
Changed to post-incrementation.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java, line 168 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-Mnf0Skv7zox0reI9q0C:-MnjTWpIBijPyiyyMVPN:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java#L168)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Took me a while to be sure what is going on here, can we just make a separate variable `correctReads`, increment it explicitly and report it if it is `> 0`?
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java, line 177 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-Mnf2InJCkgiH5Zxes3h:-MnjTZsRCersdaMZK5b0:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java#L177)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

We can make this computation lazy in the same way as `hex()`.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java, line 189 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-Mnf1bCi3fLqpuQhR54C:-MnjTtyg2LdW_8Mvl3DT:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java#L189)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

We can easily make this computation lazy making this method return an object, that will perform the hexlification when `toString()` is called on it.

```
return new Object() {
  @Override public String toString() {
    /* body of this hex method */
  }
}
```
</blockquote></details>

Done.

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/Hex.java, line 19 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-MnlD1_q529qcfvG5FrA:-MnlD1_q529qcfvG5FrB:bl03csb) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/901a0a53b477c3b1fd94e0b6d71b46d8a7e20faf/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/Hex.java#L19)):*
> ```Java
> 
> // Adapted from Apache Common Codec's Hex
> public class Hex {
> ```

This name doesn't describe the purpose of this class. What do you think about `LazyBytesHexlifier`? It still won't be obvious why is it needed, thus a comment describing where it is used will be appropriate.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/Hex.java, line 26 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-MnlE9wICzSsEoK9VCmX:-MnlE9wICzSsEoK9VCmY:b5vwww2) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/901a0a53b477c3b1fd94e0b6d71b46d8a7e20faf/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/Hex.java#L26)):*
> ```Java
>   private final byte[] bytes;
> 
>   public Hex(byte[] bytes) {
> ```

We definitely want to limit length of produced string. We should add a parameter with max length of the output string.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java, line 177 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-Mnf2InJCkgiH5Zxes3h:-MnlBWgi0G2T-ij2LPOU:bjitlpd) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java#L177)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So now we are printing a list of `Hex` objects, I don't think that it is obvious that it will work as expected and we should test that.

OTOH I thought about changing returning a object `HexList` instead of `List<Hex>` which would lazily call `for () { out.add(hex(row)); } return out;` .

Hmm, are you sure that logging lists works as expected and will print `[item1, item2]` etc? There are no tests for that (and I do not even know how to test it :D maybe we should inject our own logger implementation to be used by the logging facade and verify if it was written? or, just test it manually to be sure and assume that it is obvious that it works :D )

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/Hex.java, line 19 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-MnlD1_q529qcfvG5FrA:-MnlFfy474LInZGXlNj2:bhyc09t) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/901a0a53b477c3b1fd94e0b6d71b46d8a7e20faf/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/Hex.java#L19)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

This name doesn't describe the purpose of this class. What do you think about `LazyBytesHexlifier`? It still won't be obvious why is it needed, thus a comment describing where it is used will be appropriate.
</blockquote></details>

Well, this class is kinda obscure, maybe it'd be wise to hide it in MismatchDetector as an static inner class, wdyt?

**Review by prawilny — COMMENTED** [review]
> Dismissed @mwalkiewicz from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java, line 177 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-Mnf2InJCkgiH5Zxes3h:-Mo4R8kk7WIx8F8ajMAt:bky2w8l) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb38df3f44cd0123615638cfe8ce1660c8d25f21/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/verification/DefaultMismatchDetector.java#L177)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

So now we are printing a list of `Hex` objects, I don't think that it is obvious that it will work as expected and we should test that.

OTOH I thought about changing returning a object `HexList` instead of `List<Hex>` which would lazily call `for () { out.add(hex(row)); } return out;` .

Hmm, are you sure that logging lists works as expected and will print `[item1, item2]` etc? There are no tests for that (and I do not even know how to test it :D maybe we should inject our own logger implementation to be used by the logging facade and verify if it was written? or, just test it manually to be sure and assume that it is obvious that it works :D )
</blockquote></details>

Added a test for it (with simple string comparison).
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/Hex.java, line 19 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-MnlD1_q529qcfvG5FrA:-Mo4KXEf2uZQSEl1CQt9:bc00tlm) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/901a0a53b477c3b1fd94e0b6d71b46d8a7e20faf/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/Hex.java#L19)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Well, this class is kinda obscure, maybe it'd be wise to hide it in MismatchDetector as an static inner class, wdyt?
</blockquote></details>

I think it was extracted into a standalone class in order to accomodate some logging done in MirroringScanner#LastUnmatched, but I'll probably move LastUnmatched to MismatchDetector so I think it'll be fine as a nested class of DefaultMismatchDetector. 
Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/Hex.java, line 26 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/129#-MnlE9wICzSsEoK9VCmX:-Mo4QZRe7qCCFX0vFUSy:bmpvl7d) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/901a0a53b477c3b1fd94e0b6d71b46d8a7e20faf/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/Hex.java#L26)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

We definitely want to limit length of produced string. We should add a parameter with max length of the output string.
</blockquote></details>

Done. Also when limited it shows n/2 first bytes and n/2 last bytes (separated by "...").

**Review by mwalkiewicz — APPROVED** [review]

**Pull request merged**
