### PR TITLE
fix: BufferedMutator review fixes

### PR DESCRIPTION
**Pull request by mwalkiewicz**
- Simplify #flush().
- Add javadocs.
- (sequential) Fix flush() exception handling.
- (sequential) Move error handling to a separate inner class.

---
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164)

### CODE REVIEW

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164)* status: 0 of 3 files reviewed, 18 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 202 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnwquLEU5Vqn6PrLlT:-MqnwquLEU5Vqn6PrLlU:b-pnr7ym) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L202)):*
> ```
> the
> ```
I think this is redundant.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 205 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqnx2r30KeumFwiUdft:-Mqnx2r30KeumFwiUdfu:b-q2iks3) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L205)):*
> ```
> that was
> ```
I think this is redundant.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 205 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqnx8r088X0Uwp5XjWi:-Mqnx8r088X0Uwp5XjWj:b-alfjzo) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L205)):*
> ```
> receive exception
> ```
receive the exception
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 205 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnxHEk6i9-4Kp682wk:-MqnxHEk6i9-4Kp682wl:b-wnh8tr) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L205)):*
> ```
> We guarantee that the user will receive exception that was thrown by flush operation
> ```
Actually, perhaps we could rephrase like this:
> If the flush operation started in this method throws, we guarantee that the exception will be propagated to the user. The rationale depends on whether we use the synchronous or concurrent implementation.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 208 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqnywgl657_OJepOhmi:-Mqnywgl657_OJepOhmj:b-d7th) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L208)):*
> ```
> completion happens
> ```
is completed
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 209 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnyiAJEUe8AxuoySeR:-MqnyiAJEUe8AxuoySeS:bdk81q) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L209)):*
> ```
> what
> ```
which
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 211 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnytFw5V_HwomringZ:-MqnytFw5V_Hwomring_:b-d7th) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L211)):*
> ```
> completion happens
> ```
is completed
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 212 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnykXCA9ZTPEzFvop2:-MqnykXD4eVG6-WDVz0T:bdk81q) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L212)):*
> ```
> what
> ```
which
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 212 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnypFF20QHbzoqHLaj:-MqnypFF20QHbzoqHLak:b-rwehak) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L212)):*
> ```
> in
> ```
in the
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 379 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnzAwv1b2oZtlOjpg4:-MqnzAwv1b2oZtlOjpg5:b-2h87kk) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L379)):*
> ```
> primary
> ```
the primary
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 380 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnzGSa-SVG3aY06Sxi:-MqnzGSa-SVG3aY06Sxj:b-xbml3i) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L380)):*
> ```
> primary buffered
> ```
the primary buffered
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 385 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnzJxaCYKFnV1DEEsu:-MqnzJxaCYKFnV1DEEsv:b-4d3meo) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L385)):*
> ```
> secondary
> ```
the secondary
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 386 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnzPIY7_NbWqWKhKAK:-MqnzPIY7_NbWqWKhKAL:b-cjjymm) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L386)):*
> ```
> secondary buffered
> ```
the secondary buffered
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 397 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqo-3GH9HXJ09lGvvl2:-Mqo-3GH9HXJ09lGvvl3:bmowrns) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L397)):*
> ```
> Flush
> ```
Future
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 397 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqo-Lc_DDthCwZNNL-O:-Mqo-Lc_DDthCwZNNL-P:b-nwzzom) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L397)):*
> ```
> {@link BufferedMutator#flush()}
> ```
the {@link BufferedMutator#flush()}
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 398 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqo-R8j51KYNX1kVhAQ:-Mqo-R8k7E2THiNv97IM:b9lnxaq) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L398)):*
> ```
> asynchronous
> ```
the asynchronous
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 400 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqo0qFa-GarHuCdRtv4:-Mqo0qFa-GarHuCdRtv5:by7udu) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L400)):*
> ```
> completion
> ```
the completion
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/SequentialMirroringBufferedMutator.java, line 112 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqo1JTl2QKA2Tg3-pgD:-Mqo1JTl2QKA2Tg3-pgE:bypuume) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/SequentialMirroringBufferedMutator.java#L112)):*
> ```
> // TODO: How do we ensure that anything added before the flush (if failed) is thrown and 3 locks are
> // playing nicely with each other.
> ```
I think you answered this already

**Review by mwalkiewicz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164)* status: 0 of 3 files reviewed, 18 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 202 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnwquLEU5Vqn6PrLlT:-Mqo2a45AkWIWsfss9Xb:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L202)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> the
> ```
I think this is redundant.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 205 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqnx2r30KeumFwiUdft:-Mqo2dXO95XdysQkPszr:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L205)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> that was
> ```
I think this is redundant.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 205 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnxHEk6i9-4Kp682wk:-Mqo3dOkDxIZimRPEGC5:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L205)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> We guarantee that the user will receive exception that was thrown by flush operation
> ```
Actually, perhaps we could rephrase like this:
> If the flush operation started in this method throws, we guarantee that the exception will be propagated to the user. The rationale depends on whether we use the synchronous or concurrent implementation.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 208 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqnywgl657_OJepOhmi:-Mqo3iV15UZnPDX7GU77:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L208)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> completion happens
> ```
is completed
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 209 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnyiAJEUe8AxuoySeR:-Mqo3lId1nnJu0H0r0DS:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L209)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> what
> ```
which
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 211 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnytFw5V_HwomringZ:-Mqo3lnD-CsIAZMkMSH9:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L211)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> completion happens
> ```
is completed
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 212 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnykXCA9ZTPEzFvop2:-Mqo45ekD-07tPioqzZq:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L212)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> what
> ```
which
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 212 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnypFF20QHbzoqHLaj:-Mqo48CLDc6GrbfLdcAQ:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L212)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> in
> ```
in the
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 379 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnzAwv1b2oZtlOjpg4:-Mqo4GFG98uUbmAkwCVG:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L379)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> primary
> ```
the primary
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 380 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnzGSa-SVG3aY06Sxi:-Mqo4Gdy3O4Flf9LT7Ut:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L380)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> primary buffered
> ```
the primary buffered
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 385 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnzJxaCYKFnV1DEEsu:-Mqo4H6x2rIdv6Bys5x7:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L385)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> secondary
> ```
the secondary
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 386 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-MqnzPIY7_NbWqWKhKAK:-Mqo4H_n0Vrd0BU_SDlS:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L386)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> secondary buffered
> ```
the secondary buffered
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 397 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqo-Lc_DDthCwZNNL-O:-Mqo4Nvo1gmR0s43cPV3:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L397)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> {@link BufferedMutator#flush()}
> ```
the {@link BufferedMutator#flush()}
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 398 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqo-R8j51KYNX1kVhAQ:-Mqo4QaGA1rqzY3vaL1Q:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L398)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> asynchronous
> ```
the asynchronous
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java, line 400 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqo0qFa-GarHuCdRtv4:-Mqo4TjGAWi4UoEJT2ig:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/MirroringBufferedMutator.java#L400)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> completion
> ```
the completion
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/SequentialMirroringBufferedMutator.java, line 112 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164#-Mqo1JTl2QKA2Tg3-pgD:-Mqo4X7528emkbCda2jk:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/d5dc2e2e6b3a2ca2ab19bb1d1494355dc3fc730f/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/bufferedmutator/SequentialMirroringBufferedMutator.java#L112)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

> ```
> // TODO: How do we ensure that anything added before the flush (if failed) is thrown and 3 locks are
> // playing nicely with each other.
> ```
I think you answered this already
</blockquote></details>

Done.

**Review by dopiera — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @dopiera)

**Review by prawilny — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/164)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mwalkiewicz)

**Pull request merged**
