### PR TITLE
feat: Client-side timestamping

### PR DESCRIPTION
**Pull request by mwalkiewicz**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165)

### CODE REVIEW

**Review by dopiera — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165)* status: 0 of 38 files reviewed, 7 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[quickstart.md, line 135 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuGZLmEDVmT8UcaNqhW:-MuGZLmFBn6a-06Y3vOR:b-8aup90) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/daf5f22b62ea0d5a72631fbaac5ff547069e5668/quickstart.md#L135)):*
> ```Markdown
> 
> ## Client-side timestamping
> HBase and Bigtable assign row version (timestamp) based on server-side time for mutations without version assigned by the client. The Mirroring Client issues writes to underlying databases a few milliseconds apart and performing mutations without version assigned on the client side will cause inconsistencies between databases. To mitigate some of those issues a client-side timestamping is available in the Mirroring Client. When client-side timestamping is enabled the Mirroring Client will automatically add a timestamp based on client's local time to every `Put` object passed to the Mirroring Client. Client-side timestamps assigned by `Table`s and `BufferedMutator`s created by one `Connection` are always increasing, even if system clock is moved backwards, for example by NTP or manually by the user.
> ```

That probably goes without saying, but I think we should mention that this concerns only the mutations which do not have that timestamp explicitly set by the user.



_Code quote:_
```Markdown
to every `Put` object passed to the Mirroring Client
```
___
*[quickstart.md, line 164 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuG_r835irFpL4JlfFx:-MuG_r835irFpL4JlfFy:bwyc8ee) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/daf5f22b62ea0d5a72631fbaac5ff547069e5668/quickstart.md#L164)):*
> ```Markdown
> ## Caveats
> ### Timestamps
> Be aware that client-side timestamping modifies only `Put`s - `Delete`s, `Increment`s and `Append`s are not affected by this setting and will cause inconsistencies between databases.
> ```

Can you also add a sentence about the consequences of the time differences between the client servers?
___
*[quickstart.md, line 137 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuGmfZS8y4EgyacnqHX:-MuGmfZS8y4EgyacnqHY:bvliwe9) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c8f55cbf23668f3f12b9aa0e58d47c1ff8f317f3/quickstart.md#L137)):*
> ```Markdown
> HBase and Bigtable assign row version (timestamp) based on server-side time for mutations without version assigned by the client. The Mirroring Client issues writes to underlying databases a few milliseconds apart and performing mutations without version assigned on the client side will cause inconsistencies between databases. To mitigate some of those issues a client-side timestamping is available in the Mirroring Client. When client-side timestamping is enabled the Mirroring Client will automatically add a timestamp based on client's local time to every `Put` object passed to the Mirroring Client. Client-side timestamps assigned by `Table`s and `BufferedMutator`s created by one `Connection` are always increasing, even if system clock is moved backwards, for example by NTP or manually by the user.
> Be aware that client-side timestamping modifies only `Put`s - `Delete`s, `Increment`s and `Append`s are not affected by this setting and will cause inconsistencies between databases.
> To enable client-side timestamping set `google.bigtable.mirroring.enable-default-client-side-timestamps` to `true`.
> ```

As discussed F2F, let's make it a string with 3 valid values: "disabled", "inplace" and "copy".
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringConnection.java, line 95 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuGdLovEJf8bAxJr6ri:-MuGdLovEJf8bAxJr6rj:bs3i32y) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/daf5f22b62ea0d5a72631fbaac5ff547069e5668/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringConnection.java#L95)):*
> ```Java
> 
>   protected final boolean waitForSecondaryWrites;
>   protected final Timestamper timestamper;
> ```

Could you please add a description the all the `timestamper` fields along these lines:
```
// Depending on configuration, ensures that mutations have an explicitly set timestamp.
```
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringOptions.java, line 160 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuG_JcTCU3UcgMLwnOz:-MuG_JcTCU3UcgMLwnP-:b-80r3k7) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/daf5f22b62ea0d5a72631fbaac5ff547069e5668/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringOptions.java#L160)):*
> ```Java
> 
>     this.enableDefaultClientSideTimestamps =
>         configuration.getBoolean(MIRRORING_ENABLE_DEFAULT_CLIENT_SIDE_TIMESTAMPS, false);
> ```

I think we should set this to `inplace`. We need to pick a less bad value and I'd make the judgement call that time drifting on the servers will be a smaller issue than diverging databases.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/timestamper/MonotonicTimestamper.java, line 80 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuGkqn5EOTpyt9_c6yK:-MuGkqn5EOTpyt9_c6yL:bzcdbiu) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c8f55cbf23668f3f12b9aa0e58d47c1ff8f317f3/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/timestamper/MonotonicTimestamper.java#L80)):*
> ```Java
>           }
>         } catch (IOException e) {
>           // IOException is thrown when `cell` does not implement `SettableTimestamp` and if it
> ```

`assert false;`?
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/timestamper/Timestamper.java, line 23 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuGnTRq3WFXcb5hfH6m:-MuGnTRq3WFXcb5hfH6n:blytn15) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c8f55cbf23668f3f12b9aa0e58d47c1ff8f317f3/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/timestamper/Timestamper.java#L23)):*
> ```Java
> import org.apache.hadoop.hbase.client.RowMutations;
> 
> public interface Timestamper {
> ```

Please add a description of what it is

**Review by mwalkiewicz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165)* status: 0 of 45 files reviewed, 7 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[quickstart.md, line 164 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuG_r835irFpL4JlfFx:-MuQOVj3B8SW31B44PT4:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/daf5f22b62ea0d5a72631fbaac5ff547069e5668/quickstart.md#L164)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Can you also add a sentence about the consequences of the time differences between the client servers?
</blockquote></details>

Done.
___
*[quickstart.md, line 137 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuGmfZS8y4EgyacnqHX:-MuQGwVHCr-yhlypehQV:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c8f55cbf23668f3f12b9aa0e58d47c1ff8f317f3/quickstart.md#L137)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

As discussed F2F, let's make it a string with 3 valid values: "disabled", "inplace" and "copy".
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringConnection.java, line 95 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuGdLovEJf8bAxJr6ri:-MuQO_vb9kcTgzulehzO:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/daf5f22b62ea0d5a72631fbaac5ff547069e5668/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringConnection.java#L95)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Could you please add a description the all the `timestamper` fields along these lines:
```
// Depending on configuration, ensures that mutations have an explicitly set timestamp.
```
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringOptions.java, line 160 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuG_JcTCU3UcgMLwnOz:-MuQObO-E7TTq-RGej3W:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/daf5f22b62ea0d5a72631fbaac5ff547069e5668/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringOptions.java#L160)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

I think we should set this to `inplace`. We need to pick a less bad value and I'd make the judgement call that time drifting on the servers will be a smaller issue than diverging databases.
</blockquote></details>

Done.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/timestamper/MonotonicTimestamper.java, line 80 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuGkqn5EOTpyt9_c6yK:-MuQOoVU31-0K3KSOXQt:b-op8ubz) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c8f55cbf23668f3f12b9aa0e58d47c1ff8f317f3/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/timestamper/MonotonicTimestamper.java#L80)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

`assert false;`?
</blockquote></details>

Done. I'll throw a `new RuntimeException(e)` because `assert` would be rejected in the review.

**Review by dopiera — CHANGES_REQUESTED** [review]
> Reviewed 9 of 38 files at r1, 2 of 5 files at r2, 27 of 32 files at r3, 5 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165)* status: 43 of 45 files reviewed, 4 unresolved discussions (waiting on @dopiera and @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/MirroringConfigurationHelper.java, line 287 at r4](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuQR8tW5WaFdOoOLUCp:-MuQR8tW5WaFdOoOLUCq:bwbeoji) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/039b4994d529ce291248c390d222124be604b5f5/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/MirroringConfigurationHelper.java#L287)):*
> ```Java
>   /**
>    * Enables timestamping {@link org.apache.hadoop.hbase.client.Put}s without timestamp set based on
>    * client's host local time. Client-side timestamps assigned by {@link Table}s and {@link
> ```

Nit: local time is the time you see on your clock, i.e. time zone is needed to interpret it. Timestamp is the duration since epoch in UTC, hence it's not local.
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/timestamper/Timestamper.java, line 23 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuGnTRq3WFXcb5hfH6m:-MuQRtZR03ZD2ZFQv2qW:b-hcvrbd) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c8f55cbf23668f3f12b9aa0e58d47c1ff8f317f3/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/timestamper/Timestamper.java#L23)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Please add a description of what it is
</blockquote></details>

Ping ;)

**Review by mwalkiewicz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165)* status: 39 of 45 files reviewed, 3 unresolved discussions (waiting on @dopiera)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/timestamper/Timestamper.java, line 23 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165#-MuGnTRq3WFXcb5hfH6m:-MuQU75O2APdFif4Urrb:b-j4uc50) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/c8f55cbf23668f3f12b9aa0e58d47c1ff8f317f3/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/timestamper/Timestamper.java#L23)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Ping ;)
</blockquote></details>

Done, sorry.

**Review by dopiera — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/165)* status: 39 of 45 files reviewed, all discussions resolved (waiting on @dopiera)

**Pull request merged**
