### PR TITLE
feat: add synchronous MirroringConnection to 2.x

### PR DESCRIPTION
**Pull request by mwalkiewicz**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109)

### CODE REVIEW

**Review by prawilny — DISMISSED** [review]
Looks okay, I left some nitpicks.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109#-:-Mn0mEF5-JC5AJ_-8l0V:b-w4nbse)* status: all files reviewed, 2 unresolved discussions (waiting on @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java, line 101 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109#-Mn0kqib9iAd-WcENtj3:-Mn0kqib9iAd-WcENtj4:b-twwhxn) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/a2dd611d1319704213f8db95b0ae6b30c80e2fd1/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java#L101)):*
> ```Java
>       };
> 
>   protected final Table primaryTable;
> ```

I think it's a leftover from some WIP version.
___
*[bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringTable.java, line 30 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109#-Mn0lpgWEhKsbIVCS_JC:-Mn0lpgWEhKsbIVCS_JD:bd7v1vx) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/a2dd611d1319704213f8db95b0ae6b30c80e2fd1/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase2_x/MirroringTable.java#L30)):*
> ```Java
> import org.apache.hadoop.hbase.client.TableDescriptor;
> 
> public class MirroringTable extends com.google.cloud.bigtable.mirroring.hbase1_x.MirroringTable
> ```

Looks okay. Didn't we want to use 2.x API underneath, though?

**Review by prawilny — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109)* status: all files reviewed, 1 unresolved discussion (waiting on @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringConnection.java, line 70 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109#-Mo3wJiU8ImxGLVAM9W8:-Mo3wJiU8ImxGLVAM9W9:b-sun9fa) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb97797a8a6a07eb28fe4fd0550de6260946348b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringConnection.java#L70)):*
> ```Java
>   protected final boolean performWritesConcurrently;
>   private final boolean waitForSecondaryWrites;
> ```

Some assertion that we don't use the useless configuration of options?

**Review by prawilny — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mwalkiewicz)

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109)* status: all files reviewed, 2 unresolved discussions (waiting on @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java, line 766 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109#-Mo4-RwH0kVlZDSw4-pM:-Mo4-RwH0kVlZDSw4-pN:b-1kgy2n) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb97797a8a6a07eb28fe4fd0550de6260946348b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java#L766)):*
> ```Java
>     Object[] results = new Object[1];
>     try {
>       batchWithSpan(Collections.singletonList(operation), results);
> ```

We're don't wrap it in SpanFactory.wrapPrimaryOperation. You omitted it deliberately, right?
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java, line 831 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109#-Mo3zmnE2YancWgg0dzb:-Mo3zmnE2YancWgg0dzc:b-6m1apk) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb97797a8a6a07eb28fe4fd0550de6260946348b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java#L831)):*
> ```Java
>       this.mirroringTracer.spanFactory.wrapPrimaryOperation(primaryOperation, HBaseOperation.BATCH);
>     } catch (RetriesExhaustedWithDetailsException e) {
>       primaryBatchData.setException(e);
> ```

Why is RetriesExhausetedWithDetailsException treated differently?
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java, line 847 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109#-Mo40SkC2U6HCuRo_tUK:-Mo40SkC2U6HCuRo_tUL:bk38g5f) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb97797a8a6a07eb28fe4fd0550de6260946348b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java#L847)):*
> ```Java
>       } catch (ExecutionException e) {
>         assert false;
>         throw new IllegalStateException("secondaryResult thrown unexpected exception.");
> ```

micronit: "threw an"

**Review by prawilny — COMMENTED** [review]
I didn't remember the code so I reread it (I'm sorry for the mess in the history). Left some questions (to make sure you didn't miss them). Consider it approved after looking at those two nitty remarks.

> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109#-:-Mo429ToD1-D0kCH1RHZ:b-ejksic)* status: all files reviewed, 2 unresolved discussions (waiting on @mwalkiewicz)

**Review by mwalkiewicz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109)* status: all files reviewed, 2 unresolved discussions (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java, line 831 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/109#-Mo3zmnE2YancWgg0dzb:-Mo4SsdQ18FrvNGYbG-L:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/eb97797a8a6a07eb28fe4fd0550de6260946348b/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java#L831)):*
<details><summary><i>Previously, prawilny (Adam Czajkowski) wrote…</i></summary><blockquote>

Why is RetriesExhausetedWithDetailsException treated differently?
</blockquote></details>

Done.

**Pull request merged**
