### PR TITLE
Extract BatchHelpers to utils/

### PR DESCRIPTION
**Pull request by prawilny**
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/17)

The tests pass: https://github.com/Unoperate/java-bigtable-hbase-1/actions/runs/1257795116

### CODE REVIEW

**Review by dopiera — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @prawilny)

**Comment by prawilny** [comment]
Merging PR this one depended upon into master somehow caused conflicts :shrug:
Force-pushed after a rebase.

**Comment by prawilny** [comment]
I added an additional argument: `Predicate<Object>` that checks whether a result (stored in `Object[]`) is faulty. That allows me to reuse the code in 2.x's `batch()`.
Also changed base to utils.reflection so that merges of PRs up to the batch() one may be easily linearized.

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/17)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dopiera)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java, line 608 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/17#-MkMJzDC5mG4IOY8r8hb:-MkMJzDD12791PA8ihN9:b-4gsz6o) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/2eed126dee34f81a65176de388c9b2f11ad1b58d/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/MirroringTable.java#L608)):*
> ```Java
>   }
> 
>   private void scheduleSecondaryWriteBatchOperations(
> ```

I'd like to reuse this code -  it will be identical in 2.x's `batch()` with difference only in last call - the scheduling.
How to do it? Should I create an interface `RequestScheduler` that has some common part of `RequestScheduling#scheduleVerificationAndRequestWithFlowControl` and `MirroringAsyncTable#reserveFlowControlResourcesThenScheduleSecondary` or is a wrapper around these classes or just pass a two-argument lambda into this function?

**Review by mwalkiewicz — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dopiera)

**Review by mwalkiewicz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dopiera)

**Pull request merged**
