### PR TITLE
refactor: rename WRITE_MISMATCH to SECONDARY_WRITE_ERROR

### PR DESCRIPTION
**Pull request by prawilny**
Requested here https://github.com/Unoperate/java-bigtable-hbase-1/pull/129#pullrequestreview-797713124

---
This change is [Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138)

### CODE REVIEW

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @mwalkiewicz and @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java, line 57 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138#-Mnkwg238QJDvPV-lP7t:-Mnkwg238QJDvPV-lP7u:b-avp1iv) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/18e838d0c59a5b864e721919d5c0643f7c95f616/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java#L57)):*
> ```
> /mismatch/
> ```
`/mismatch/` part in the path is not valid now after the rename.

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138)* status: all files reviewed, 2 unresolved discussions (waiting on @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringMetricsViews.java, line 92 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138#-Mo3le8c11GJKHoJApI0:-Mo3le8c11GJKHoJApI1:b-df6a3d) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/9a00898d26654e89c4fcdb9a11a829e4afc1a93a/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringMetricsViews.java#L92)):*
> ```Java
>           ImmutableList.of(OPERATION_KEY));
> 
>   /** {@link View} for Mirroring client's secondary database write errors. */
> ```

I do not think that this move is necessary, even though the name of this view starts with `secondary`
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java, line 57 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138#-Mnkwg238QJDvPV-lP7t:-Mo3lrfr3ob-QcutgamA:b3kre) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/18e838d0c59a5b864e721919d5c0643f7c95f616/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java#L57)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

> ```
> /mismatch/
> ```
`/mismatch/` part in the path is not valid now after the rename.
</blockquote></details>

?

**Review by mwalkiewicz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138)* status: all files reviewed, 2 unresolved discussions (waiting on @prawilny)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java, line 57 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138#-Mnkwg238QJDvPV-lP7t:-Mo3nRB7BWa11kY3qHPu:b-tcqf8d) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/18e838d0c59a5b864e721919d5c0643f7c95f616/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java#L57)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

?
</blockquote></details>

Well, it is ok, sorry for that. I'd also move this one back to it's place.

**Review by prawilny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @mwalkiewicz)

___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringMetricsViews.java, line 92 at r2](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138#-Mo3le8c11GJKHoJApI0:-Mo3nmhOB4ejZnWjh4eN:b-8uetm2) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/9a00898d26654e89c4fcdb9a11a829e4afc1a93a/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringMetricsViews.java#L92)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I do not think that this move is necessary, even though the name of this view starts with `secondary`
</blockquote></details>

Done (but make sure to check the full diff).
___
*[bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java, line 57 at r1](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138#-Mnkwg238QJDvPV-lP7t:-Mo3oDaU5cGCp1hbRQe2:b-896fix) ([raw file](https://github.com/unoperate/java-bigtable-hbase-1/blob/18e838d0c59a5b864e721919d5c0643f7c95f616/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x/src/main/java/com/google/cloud/bigtable/mirroring/hbase1_x/utils/mirroringmetrics/MirroringSpanConstants.java#L57)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

Well, it is ok, sorry for that. I'd also move this one back to it's place.
</blockquote></details>

Done.

**Review by mwalkiewicz — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @prawilny)

**Review by mwalkiewicz — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/java-bigtable-hbase-1/138)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @prawilny)

**Pull request merged**
